version: "3.9"
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
          - 5432:5432
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sql-server-db
        ports:
          - 1433:1433
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: "Password123"